before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: .

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: javaman
    homepage: "https://github.com/developerdh/javaman"
    description: "A Java Version Manager by Shenzhen Aide Digital Intelligence"
    license: "MIT"
    tap:
      owner: developerdh
      name: homebrew-tools
    folder: Formula
    install: |
      bin.install "javaman"
    test: |
      system "#{bin}/javaman", "--version"

release:
  draft: true
